server:
  port: 8080

spring:
  freemarker:
    suffix: .html
    request-context-attribute: request

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456

smart:
  sso:
    server:
      timeout: 7200 #单点登录超时时间，默认2小时（单位秒）