server:
  port: 8080

logging:
  level:
    root: info

spring:
  freemarker:
    suffix: .html
    request-context-attribute: request

  datasource: #数据库连接(可选，smart-stage-starter-mybatisplus时必选)
    url: jdbc:mysql://127.0.0.1:3306/smart-sso?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456

smart:
  sso:
    #服务端地址
    server-url: http://server.smart-sso.com:8080
    #客户端应用信息
    client-id: smart-sso-server
    client-secret: 123456
    #忽略拦截urls
    exclude-urls: /static/*,/sso/*
    #单点登录超时时间，默认2小时，单位秒（服务端独有配置）
    server:
      timeout: 7200